In [1]:
import numpy as np

In [18]:
ar_rand=np.array([12,34,54,5,68,66,5,45,54,76,89,32])
print("Array",ar_rand)

Array [12 34 54  5 68 66  5 45 54 76 89 32]


In [19]:
ar_rand>7

array([ True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True])

In [20]:
np.where(ar_rand>10) #returns the position/index where the condition is true

(array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11]),)

In [21]:
ar_rand[np.where(ar_rand>10)]

array([12, 34, 54, 68, 66, 45, 54, 76, 89, 32])

In [22]:
np.where(ar_rand>10,"G5","L5")

array(['G5', 'G5', 'G5', 'L5', 'G5', 'G5', 'L5', 'G5', 'G5', 'G5', 'G5',
       'G5'], dtype='<U2')

In [42]:
ar_rand

array([12, 34, 54,  5, 68, 66,  5, 45, 54,  2,  8, 32])

In [33]:
grades=np.where(ar_rand<35,"F",
         np.where(ar_rand<45,"D",
         np.where(ar_rand<60,"C",
         np.where(ar_rand<80,"B",
         np.where(ar_rand<90,"A","A")
         )))
         )


In [35]:
print(grades)

['F' 'F' 'C' 'F' 'B' 'B' 'F' 'C' 'C' 'B' 'A' 'F']


In [ ]:

idx = np.argmax(ar_rand)
ar_rand[idx] = 2
print("Max_value", ar_rand[idx])

Max_value 2


In [38]:
print("Max_value",np.argmax(ar_rand))

Max_value 10


In [56]:
a=np.zeros([5,5])
b=np.ones([5,5])
a,b

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [57]:
out=np.concatenate([a,b],axis=1)
out

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [48]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [60]:
np.r_[a,b]  #aligns with rows

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.c_[a,b]  #aligns with columns

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

[]is used to extract the data and creating data too


()function,method,classes

In [94]:
arr=np.random.randint(1,6,size=[4,5])
arr

array([[3, 3, 1, 1, 3],
       [4, 5, 5, 1, 4],
       [3, 4, 5, 4, 5],
       [2, 4, 2, 3, 1]], dtype=int32)

In [85]:
np.mean(arr,axis=0) #column wise mean

array([3.5 , 2.  , 2.  , 2.75, 3.25])

In [86]:
np.mean(arr,axis=1) #row wise mean

array([2.6, 2.2, 3. , 3. ])

In [87]:
np.mean(arr,axis=-1) #same as 1

array([2.6, 2.2, 3. , 3. ])

In [96]:
arr

array([[3, 3, 1, 1, 3],
       [4, 5, 5, 1, 4],
       [3, 4, 5, 4, 5],
       [2, 4, 2, 3, 1]], dtype=int32)

In [98]:
np.sort(arr,axis=0)

array([[2, 3, 1, 1, 1],
       [3, 4, 2, 1, 3],
       [3, 4, 5, 3, 4],
       [4, 5, 5, 4, 5]], dtype=int32)

In [97]:
np.sort(arr,axis=1)

array([[1, 1, 3, 3, 3],
       [1, 4, 4, 5, 5],
       [3, 4, 4, 5, 5],
       [1, 2, 2, 3, 4]], dtype=int32)

In [100]:
arr

array([[3, 3, 1, 1, 3],
       [4, 5, 5, 1, 4],
       [3, 4, 5, 4, 5],
       [2, 4, 2, 3, 1]], dtype=int32)

In [ ]:
a=np.array([1,2,5,87,34,32])
sort_index=np.argsort(a)
sort_index      #does not sort the values of array it sorts the index of the array

array([0, 1, 2, 5, 4, 3])

In [103]:
a[sort_index]   #returns the  sorted values of the array

array([ 1,  2,  5, 32, 34, 87])

In [104]:
arrr=np.random.randint(1,6,size=[8,5])

In [109]:
arrr

array([[4, 3, 1, 5, 2],
       [3, 3, 3, 1, 3],
       [4, 3, 2, 1, 4],
       [4, 4, 2, 5, 4],
       [3, 2, 1, 3, 3],
       [4, 3, 4, 1, 1],
       [1, 5, 5, 5, 4],
       [4, 4, 2, 1, 4]], dtype=int32)

In [110]:
arrr[:,0]

array([4, 3, 4, 4, 3, 4, 1, 4], dtype=int32)

In [111]:
sorted_index_1col=arrr[:,0].argsort()
sorted_index_1col

array([6, 1, 4, 0, 3, 2, 5, 7])

In [112]:
arrr[sorted_index_1col]

array([[1, 5, 5, 5, 4],
       [3, 3, 3, 1, 3],
       [3, 2, 1, 3, 3],
       [4, 3, 1, 5, 2],
       [4, 4, 2, 5, 4],
       [4, 3, 2, 1, 4],
       [4, 3, 4, 1, 1],
       [4, 4, 2, 1, 4]], dtype=int32)

In [114]:
arrr[sorted_index_1col[::-1]] #descending order sort 

array([[4, 4, 2, 1, 4],
       [4, 3, 4, 1, 1],
       [4, 3, 2, 1, 4],
       [4, 4, 2, 5, 4],
       [4, 3, 1, 5, 2],
       [3, 2, 1, 3, 3],
       [3, 3, 3, 1, 3],
       [1, 5, 5, 5, 4]], dtype=int32)

In [118]:
arr

array([[3, 3, 1, 1, 3],
       [4, 5, 5, 1, 4],
       [3, 4, 5, 4, 5],
       [2, 4, 2, 3, 1]], dtype=int32)

In [117]:
lexsort_index=np.lexsort((arr[:,0],arr[:,1]))
lexsort_index

array([0, 3, 2, 1])