In [2]:
import numpy as np

In [4]:
var=np.array(2,20,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
type(var)

In [7]:
l1=[1,2,3,4,5]
arr1=np.array(l1)
arr1.dtype

dtype('int64')

In [9]:
l2=[3,6,2,5.5,8]
arr2=np.array(l2)
arr2.dtype

dtype('float64')

In [13]:
arr3=np.array(["1","2","3","4"],dtype="int")
arr3

array([1, 2, 3, 4])

In [18]:
arr3.astype("str")

array(['1', '2', '3', '4'], dtype='<U21')

In [19]:
arr1+arr2

array([ 4. ,  8. ,  5. ,  9.5, 13. ])

In [22]:
arr1.shape
arr2.shape

(5,)

In [25]:
#generate 3 d array
ar3=np.array([[[1,2,3],[4,5,6],[13,14,15]],[[7,8,9],[10,11,12],[16,17,18]]])
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [16, 17, 18]]])

In [26]:
ar3.shape, ar3.ndim

((2, 3, 3), 3)

In [ ]:
#generate array 3d array of dimension 4*4
ar4=np.array([[[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]],
                [[17,18,19,20],
                 [21,22,23,24],
                 [25,26,27,28],
                 [29,30,31,32]],
                 [[33,34,35,36],
                  [37,38,39,40],
                  [41,42,43,44],
                  [45,46,47,48]],
                  [[49,50,51,52],
                   [53,54,55,56],
                   [57,58,59,60],
                   [61,62,63,64]]]])
ar4

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]],

        [[49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]]]])

In [35]:
ar4.shape,ar4.ndim

((1, 4, 4, 4), 4)