import numpy as np

In [1]:
import numpy as np

In [28]:
threeD=np.array([[50,3,4,2],[7,61,4,3]])
threeD

array([[50,  3,  4,  2],
       [ 7, 61,  4,  3]])

In [29]:
d3=np.array([[9,87,6,5],[3,54,22,65]])
d3

array([[ 9, 87,  6,  5],
       [ 3, 54, 22, 65]])

if the condition is applied to the array it displays the output in the boolean form


In [30]:
threeD>25

array([[ True, False, False, False],
       [False,  True, False, False]])

In [31]:
d3>22

array([[False,  True, False, False],
       [False,  True, False,  True]])

In [32]:
threeD[threeD>25]

array([50, 61])

if condition is matched it returns the position of the element in the first array

In [33]:
d3[threeD>25]

array([ 9, 54])

In [34]:
arr=np.arange(10,30)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [38]:
arr[1]

np.int64(11)

In [36]:
arr[5:10]

array([15, 16, 17, 18, 19])

In [39]:
arr_slice=arr[5:8]
arr_slice[1]=90

In [40]:
arr_slice

array([15, 90, 17])

In [42]:
arr[5:8]

array([15, 90, 17])

In [62]:
arr_slice=arr[-3:]
arr_slice

array([27, 28, 29])

In [64]:
arr_slice[2]=200
arr_slice

array([ 27,  28, 200])

In [53]:
arr_slice1=arr[10:15].copy()

In [54]:
arr_slice1

array([20, 21, 22, 23, 24])

In [110]:
list_arr=np.arange(1,21)

In [111]:
list_arr1=list_arr.reshape(5,4)
list_arr1,list_arr1.ndim,list_arr1.shape


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 2,
 (5, 4))

In [112]:
flat_arr=list_arr1.reshape(4,5)
flat_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Flatten is creating a copy as a 1D array

In [124]:
a=flat_arr.flatten()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [125]:
a.shape,a.ndim

((20,), 1)

In [126]:
a[1]=200

In [127]:
a

array([  1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [128]:
flat_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Ravel is reshaping the array into 1D array and ravel make changes directly to the main array

In [129]:
b=list_arr1.ravel()

In [130]:
b[3]=99

In [131]:
b

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [133]:
list_arr1.flatten()

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [135]:
names=np.array(['Narendra','Aditya','Harsh','Niraj','Harsh','Mohit','Om'])
data=np.random.randint(30,100,size=(7,4))

In [154]:
print("Shape of Names",names.shape)
print("Shape of data",data.shape)   #rows size should be the same column size does not matter much

Shape of Names (7,)
Shape of data (7, 4)


In [155]:
data

array([[34, 49, 38, 53],
       [64, 89, 90, 88],
       [47, 83, 31, 94],
       [89, 40, 35, 96],
       [55, 75, 56, 74],
       [95, 40, 47, 31],
       [99, 89, 35, 55]], dtype=int32)

In [156]:
names=='Harsh'              #returns rows of the condition

array([False, False,  True, False,  True, False, False])

In [ ]:
data[names=='Harsh']

array([31, 56], dtype=int32)

In [158]:
data[(names=='Harsh')|(names=='Narendra')]

array([[34, 49, 38, 53],
       [47, 83, 31, 94],
       [55, 75, 56, 74]], dtype=int32)

In [159]:
data[(names=='Harsh')&(names=='Narendra')]

array([], shape=(0, 4), dtype=int32)

In [161]:
data[names=='Harsh',2]

array([31, 56], dtype=int32)

In [162]:
x=names=='Harsh'

In [163]:
x


array([False, False,  True, False,  True, False, False])

In [173]:
data[x,:][:,1:3]

array([[83, 31],
       [75, 56]], dtype=int32)

In [174]:
data[(names!='Harsh'),:]

array([[34, 49, 38, 53],
       [64, 89, 90, 88],
       [89, 40, 35, 96],
       [95, 40, 47, 31],
       [99, 89, 35, 55]], dtype=int32)

In [177]:
x

array([False, False,  True, False,  True, False, False])

In [178]:
~x

array([ True,  True, False,  True, False,  True,  True])

In [176]:
data[~x,:]

array([[34, 49, 38, 53],
       [64, 89, 90, 88],
       [89, 40, 35, 96],
       [95, 40, 47, 31],
       [99, 89, 35, 55]], dtype=int32)

In [185]:
f=arr

In [186]:
f

array([ 10,  11,  12,  13,  14,  15,  90,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28, 200])

In [187]:
np.sqrt(f)

array([ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  9.48683298,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262, 14.14213562])

In [188]:
np.log(f)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 4.49980967, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 5.29831737])

In [190]:
np.exp(f)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 1.22040329e+39, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
       3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
       1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 7.22597377e+86])

In [218]:
arr=arr.astype("float32")
arr[1]=np.nan

In [219]:
arr

array([ 10.,  nan,  12.,  inf,  inf,  15.,  nan,  inf,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28., 200.],
      dtype=float32)

In [211]:
np.isnan(arr)

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [212]:
sum(np.isnan(arr))

np.int64(2)

In [230]:
cond=np.isnan(arr)|np.isinf(arr)

In [231]:
cond

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [232]:
arr[cond]=-800

In [233]:
arr

array([  10., -800.,   12., -800., -800.,   15., -800., -800.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,  200.], dtype=float32)

In [237]:
x=np.random.randint(1,10,size=10)

In [238]:
x

array([5, 9, 4, 2, 3, 4, 1, 6, 8, 6], dtype=int32)

In [239]:
y=np.random.randint(1,10,size=10)

In [240]:
y

array([8, 5, 4, 9, 5, 2, 4, 8, 7, 2], dtype=int32)

In [241]:
z=np.random.randint(1,10,size=10)

In [242]:
np.maximum(x,y)

array([8, 9, 4, 9, 5, 4, 4, 8, 8, 6], dtype=int32)

In [243]:
np.minimum(x,z)

array([5, 9, 4, 2, 2, 4, 1, 6, 6, 5], dtype=int32)